### ISSUE TITLE
Java 17.  Unsupported class file major version 61

### ISSUE THREAD

**Issue by Osmyslitelny** [Drill4J/test2code-plugin#306]
Problem with jdk 17.
Error:

```
java.io.IOException: Error while analyzing com/mkyong/HelloController.
        at com.epam.drill.plugins.test2code.shadow.org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:162)
        at com.epam.drill.plugins.test2code.shadow.org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:134)
        at com.epam.drill.plugins.test2code.jvm.JacocoExtKt$bundle$2.invoke(JacocoExt.kt:53)
        at com.epam.drill.plugins.test2code.jvm.JacocoExtKt$bundle$2.invoke(JacocoExt.kt)
        at com.epam.drill.plugins.test2code.jvm.JacocoExtKt.bundle(JacocoExt.kt:62)
        at com.epam.drill.plugins.test2code.jvm.JacocoExtKt.bundle(JacocoExt.kt:52)
        at com.epam.drill.plugins.test2code.AgentState.initialized(State.kt:123)
        at com.epam.drill.plugins.test2code.Plugin.processData(Plugin.kt:239)
        at com.epam.drill.plugins.test2code.Plugin.processData(Plugin.kt:218)
        at com.epam.drill.admin.endpoints.plugin.PluginDispatcher.processPluginData(PluginDispatcher.kt:76)
        at com.epam.drill.admin.endpoints.agent.AgentHandler$createWsLoop$$inlined$consumeEach$lambda$4.invokeSuspend(AgentHandler.kt:105)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
        at com.epam.drill.plugins.test2code.shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
        at com.epam.drill.plugins.test2code.shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
        at com.epam.drill.plugins.test2code.shadow.org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
        at com.epam.drill.plugins.test2code.shadow.org.jacoco.core.internal.instr.InstrSupport.classReaderFor(InstrSupport.java:280)
        at com.epam.drill.plugins.test2code.shadow.org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:107)
        at com.epam.drill.plugins.test2code.shadow.org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:132)
        ... 15 common frames omitted
```

Reproducing:
Setup java 17 for build.
Create app on jdk 17 (for testing I get open hello world). 
https://github.com/mkyong/spring-boot/tree/master/spring-boot-hello-world
```
mvn clean install
```
Create image for docker-compose testing:
Add to folder Dokcerfile
```
FROM openjdk
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
```
Create image
```
docker run --rm -p 8080:8080 spring_hello
```
Create docker-compose file:
```
version: '3.9'

services:
  admin-ui:
    image: drill4j/admin-ui:0.8.0-alpha
    ports:
      - "8091:8080"

  drill-admin:
    image: drill4j/admin:0.8.0-alpha.1
    environment:
      - TEST2CODE_PLUGIN_VERSION=0.8.0-alpha.1
      - LOG_LEVEL=INFO
    ports:
      - "8090:8090"

  agent-files:
    image: drill4j/java-agent:0.8.0-alpha.1
    volumes:
      - agent-files:/data

  spring_hello:
    image: spring_hello:latest
    ports:
      - "8080:8080"
    environment:
      - "JAVA_TOOL_OPTIONS=-agentpath:/data/agent/libdrill_agent.so=drillInstallationDir=/data/agent,adminAddress=host.docker.internal:8090,agentId=SpringHello,buildVersion=0.1.0,logLevel=INFO"
    volumes:
      - agent-files:/data

volumes:
  agent-files:
```
Run compose (rerun command if spring doesnt start. (volume should be create before)
```
docker-compose up -d
```

Open drill UI, setup configuration. (1st point: plugin doesnt find any code/functions)
Open localhost:8080 and check spring application.
Use extension for running manual test. (Do few execs and finish test).
Check drill drill-admin logs (docker logs ... drill-admin_1_container_name).

**Comment by Mazel-Tovr** [comment]
Thanks for the issue , it looks like we should update the jacoco library version to the latest.

**Comment by Mazel-Tovr** [comment]
Also support java 17 in :
1. Java agent - from 0.8.0-30
2. Autotest agent -from 0.17.8
